### ISSUE TITLE
Selector that invokes another selector? (not an input selector)

### ISSUE THREAD

**Issue by jordan-enev** [reduxjs/reselect#353]
[The question is asked in SO](https://stackoverflow.com/q/50965013/4312466) these days (not by me) and I think it deserves more attention. :)

I faced similar limitations as many times I'm handling relational data with `reselect`, and because of this I already contributed my approaches.

However, I'm wondering are there any other solutions / approaches? (it would be better to contribute in SO directly).

Thanks. :heart:

**Comment by dtinth** [comment]
I have [posted my answer](https://stackoverflow.com/a/51973044/559913) on the SO thread. It is reproduced below:

A problem we faced when using `reselect` is that **there is no support for dynamic dependency tracking.** A selector needs to declare upfront which parts of the state will cause a recomputation.

For example, I have a list of online user IDs, and a mapping of users:

```js
{
  onlineUserIds: [ 'alice', 'dave' ],
  notifications: [ /* unrelated data */ ]
  users: {
    alice: { name: 'Alice' },
    bob: { name: 'Bob' },
    charlie: { name: 'Charlie' },
    dave: { name: 'Dave' },
    eve: { name: 'Eve' }
  }
}
```

I want to select a list of online users, e.g. `[ { name: 'Alice' }, { name: 'Dave' } ]`.

Since I cannot know upfront which users will be online, I need to declare a dependency on the whole `state.users` branch of the store.

![Example 1](https://user-images.githubusercontent.com/193136/44481470-0b3e9980-a670-11e8-82b6-6e0aac6449ef.png)

This works, but this means that changes to unrelated users (bob, charlie, eve) will cause the selector to be recomputed.

I believe this is a problem in reselect’s fundamental design choice: dependencies between selectors are **static.** (In contrast, Knockout, Vue and MobX do support dynamic dependencies.)

We faced the same problem and we came up with [`@taskworld.com/rereselect`](https://github.com/taskworld/rereselect). Instead of declaring dependencies upfront and statically, dependencies are collected just-in-time and dynamically during each computation:

![a2](https://user-images.githubusercontent.com/193136/44482148-d16e9280-a671-11e8-88cd-e8eca3887a37.png)

This allows our selectors to have a more fine-grained control over which parts of state can cause a selector to be recomputed.

**Comment by jvitela** [comment]
[Recompute](https://github.com/jvitela/recompute) is an alternative to reselect (and very similar to rereselect) It implements dynamic dependency tracking and allows any number of arguments to be passed to the selector, you could check if this would solve your problem
