### ISSUE TITLE
Is it okay to have selectors returning functions?

### ISSUE THREAD

**Issue by tkrugg** [reduxjs/reselect#357]
```js
const getUsers = state => state.users
// state.users = [
//    { id: 1, locales: ['fr-FR', 'en-GB'] },
//    { id: 2, locales: ['fr-FR', 'en-US'] },
//    { id: 3, locales: ['fr-FR', 'en-US'] },
// ]

const getLocalesForUsers = createSelector(
   getUsers,
   users => 
     userIds => new Set(
         users
            .filter(user => userIds.includes(user.id))
            .map(user => user.locales)
       )
)


const mapStateToProps = state => ({
    locales: getLocalesForUsers([1, 2])
})
```

**Comment by joedski** [comment]
It's a perfectly valid pattern, I use it quite frequently to do more or less what you've done there, inject a slice of state without passing the state itself around, but it does have some caveats: You must pay close attention to what you're trying to memoize.

Reselect doesn't have any special handling of returned functions, it only computes this new function from the given values, treating that function as the result value.  Particularly, it does not automatically memoize that returned function, you have to create a memoized function yourself.

Your own case might be rewritten as:

```js
const getLocalesForUsers = createSelector(
  getUsers,
  users => lodash.memoize(userIds => ...)
)
```

But that will only work if you actually keep the input array somewhere rather than creating a new one every redraw.  Handling array inputs is another separate can of worms.

**Comment by tkrugg** [comment]
good point @joedski ! thank you very much
