### ISSUE TITLE
Is there any way to apply different equality checks on different arguments

### ISSUE THREAD

**Issue by anuprai11** [reduxjs/reselect#379]
https://github.com/reduxjs/reselect/blob/8c55f18e1528022b25e19aa19321e6cdda06eea5/src/index.js#L12

think about a condition where you have a function func( a: array[int], s: string)
and I want to use it inside defaultMemoize then what can I do. I mean the equality function is called for each argument without even giving the index of the argument or any indication  where the argument lies.
If we could give the whole list of argument to the equality check that could be better other wise giving the index of the argument might be good.

**Comment by c-dante** [comment]
I'd prefer giving the index of the check as an argument as opposed to an array of functions for each argument. Definitely don't like equality function being passed the whole list.

As a short term for your specific example, lodash's `isEqual` method reflects to determine equality, so that would handle your case. You could, of course, write different equality checks based on type if you need.
