### ISSUE TITLE
Will useMemo replace reselect?

### ISSUE THREAD

**Issue by coryhouse** [reduxjs/reselect#386]
Is there anything reselect offers that [useMemo](https://reactjs.org/docs/hooks-reference.html#usememo) can't handle?

**Comment by vinnymac** [comment]
With only a cursory glance, I would assume that `useMemo` cannot replace `reselect` simply because `useMemo` is a hook and therefore will only work with functional components. While `reselect` works with any type of component.

As far as I know the original intent was to couple `reselect` with `react-redux`. Seeing as they plan on adding support for some kind of `useRedux` like functionality in `react-redux` I'd figure that could be coupled with `useMemo` eventually. I am pretty sure to get a real answer to your question we will have to wait to see what it is exactly `react-redux` creates in regards to a hook, and whether or not that works well with `useMemo`.

With that said, `reselect` can be used anywhere, as it has [no dependencies](https://github.com/reduxjs/reselect#q-can-i-use-reselect-without-redux). So if it was necessary to use with a theoretical new hook instead of `connect()`, it may be able to be repurposed for that use case.

**Comment by markerikson** [comment]
Reselect is indeed useful anywhere.  Really, its competition is libs like `memoize-one`, not `useMemo()`.  

For Redux usage, we recommend using selectors _anywhere_ you access the Redux state tree, not just in `mapState` functions.  That includes thunks, sagas, middleware, and so on.  See my post [Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance](https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/) for more details.

**Comment by coryhouse** [comment]
Ha, I dunno what I was thinking. I know Hooks only work in React components. Sigh. Thanks for your patience and the excellent response guys! 👍 

Closing. :)

**Comment by enoh-barbu** [comment]
But in terms of using it within react apps, will there be any reasons for not replacing it with memo hooks?

**Comment by AndrewCraswell** [comment]
Yes, I think this is a worthwhile question still. Given a FunctionComponent, is there any reason to use reselect over useMemo?

**Comment by Kadrian** [comment]
One stylistic difference is: with `reselect` and e.g. `react-redux` your component rerenders only when a selected/memoized value changes. With `useMemo`, the component renders anyways. Yes, you could create a wrapper / HOC that renders your component and use useMemo in there. That's essentially what react-redux's `connect` does. So well. To me at least, it seems to be a matter of individual taste

**Comment by pavan-shipmnts** [comment]
But rendering is not the same as commit in react terms. For detailed explanation on the same
https://kentcdodds.com/blog/fix-the-slow-render-before-you-fix-the-re-render

**Comment by supnate** [comment]
No, they are different. `useMemo` memorizes data per instance but `reselect` is global.

**Comment by mrdulin** [comment]
> No, they are different. `useMemo` memorizes data per instance but `reselect` is global.

I'm curious whether the memory usage of useMemo() will be greater than that of selector if there are a lot of instances.
