### ISSUE TITLE
How to access second selector with custom selector

### ISSUE THREAD

**Issue by DominicTobias** [reduxjs/reselect#395]
Hi,

I followed the docs and I'm quite confused when implementing the following custom selector:

```js
const createDeepEqualSelector = createSelectorCreator(
  defaultMemoize,
  (...args) => {
    console.log('===== a', args);
    return false;
  },
  (...args) => {
    console.log('===== b', args);
    return false;
  },
)

export const someSelector = createDeepEqualSelector(
  [someSelectorA, someSelectorB],
  (a, b) => {...}
);
```

The reality is that the console log `'===== a'` is receiving the previous and current output from `someSelectorA`, but `'===== b'` is never even called.

How do I check for `someSelectorB` output? Thanks

**Comment by markerikson** [comment]
This looks like an incorrect use of `createSelectorCreator`.

`createSelectorCreator`'s first arg should be the memoization function you want to use.  All remaining arguments should be the actual parameters of that memoization function.  `createSelectorCreator` later does `memoizeFunction(newSelector, ...memoizationArgs)`.

`defaultMemoize` only takes one argument: the `equalityCheck` function you want to use.

You are passing _two_ functions here.  So yes, the second function will never be used, because `defaultMemoize` only ever expects and uses _one_ equality comparison function.
