### ISSUE TITLE
Props arguments are not been passed to the the selector created by createSelector

### ISSUE THREAD

**Issue by krvajal** [reduxjs/reselect#402]
I see from this line 
https://github.com/reduxjs/reselect/blob/master/src/index.js#L68
that the returned selector has arity 0, 
which does not play well when used with the `redux-form` library, for example, something like this
```
import {form} from 'redux-form'
import {createStructuredSelector} from 'reselect'
const withRegisterForm = form({
		form: 'register', 
		fields: ['name']
	}, createStructuredSelector({
		initialValues: customSelectorHere
	})
```

the second argument to `form` is a `mapStateToProps` like function, but it is only passing the state and not the props because the selector created by `createStructuredSelector` is inaccurately reporting its arity as zero

**Comment by josepot** [comment]
Hi @krvajal ,

IMO what you are describing here is a problem with `redux-form`, because the only occasion where it is safe to just pass the state to a selector (without the rest of args) is **when the arity is one**.

There are lots of valid cases for creating selectors that return an arity of zero. An arity of zero should be interpreted as: "it must be using all the arguments", not as "it's just using the first argument".

**Comment by krvajal** [comment]
Fair enough. I already created a fix on [redux-form](https://github.com/erikras/redux-form)
