### ISSUE TITLE
Why render() is called continuously when i use createSelector() outside mapStateToProps ?

### ISSUE THREAD

**Issue by arunkandregula** [reduxjs/reselect#409]
For the [reselect-redux example](https://github.com/brigand/react-scratch/tree/master/src/reselect-redux), its not clear why the following pattern works for Case1, but doesnt work for Case2.

I see correct output both Case1 and Case2.
The render method of PostsByUser is called only once in Case1. Which is expected with this library.
But the render method of PostsByUser is being called repeatedly in Case2.
Is it a bug in Case2?

Case1
```js
const mapState = () => {
  const getPostsForUser = createSelector(
    (state, props) => props.user,
    (state) => state.postsById,
    (state) => state.usersById,
    (state) => state.postListing,
    (userId, posts, users, listing) => listing
      .filter(id => posts[id].author === userId)
      .map(id => {
        const post = posts[id];
        return { ...post, user: users[post.author] }
      }),
  );

  return (state, ownProps) => {
    return { posts: getPostsForUser(state, ownProps) };
  };
}

export default connect(mapState)(Posts);
```

Case2: 
```js
const getPostsForUser = createSelector(
  (state, props) => props.user,
  (state) => state.postsById,
  (state) => state.usersById,
  (state) => state.postListing,
  (userId, posts, users, listing) => listing
    .filter(id => posts[id].author === userId)
    .map(id => {
      const post = posts[id];
      return { ...post, user: users[post.author] }
    }),
);

const mapState = () => {
  return (state, ownProps) => {
    return { posts: getPostsForUser(state, ownProps) };
  };
}

export default connect(mapState)(Posts);
```

**Comment by TotooriaHyperion** [comment]
It's expected behavior.

In case 2, you create a normal anonymous function that don't memoize anything, and inside your anonymous function, you use same selector across multiple instances.

Remember **any selector depends on props** should be created **inside the mapState function**.

**Comment by TotooriaHyperion** [comment]
@markerikson 
I don't see significant contradiction between our points.
His question is why using createSelector() outside mapStateToProps cause memoization don't work.
The problem is selector default has a memory length of 1. So it's better to keep every component instance with a unique selector.

When use connect, pass mapState as a function that returns a function where you use createSelector will automatically create a unique selector. But if you create it outside the mapState, there won't be a unique selector for each componnet instance.
That's what I mean to "selector depends on props should be created inside the mapState function" -- make sure to create a unique selector inside the mapState function(so-called factory function syntax).

When use hooks, use useCallback to create a unique selector that may depends on props or other data related to that component instance.

That's how to achieve "make sure every component instance with a unique selector".
I just answer him with the connect function.
