### ISSUE TITLE
Persist memoization

### ISSUE THREAD

**Issue by nxz91** [reduxjs/reselect#411]
Hi everyone,

how can I make reselect persist to disk with redux-persist? Does this make any sense from a performance standpoint?

Thanks!
Leonard

**Comment by calvinkei** [comment]
+1 for this

**Comment by markerikson** [comment]
The statement doesn't make sense.

_What_ are you wanting to persist?  How?  This really doesn't seem like it has anything to do with Reselect at all.  I don't know how you would "persist a selector".

**Comment by calvinkei** [comment]
@markerikson the use case is when you open the app, the selector will always run once before it will be cached for future selection. by using redux persist we can persist the cache even if the app is reloaded

**Comment by markerikson** [comment]
That's not what selectors are for.  Selectors are not about external persistence.  Selectors are about encapsulating looking up specific values from the state tree, and caching derived values so that if you call the selectors again with the same inputs, the derived values don't have to be recalculated again.

Sorry, but what you're describing there seems like a misunderstanding of how selectors work.
