### ISSUE TITLE
[Question] Is there value in memoizing 100+ selectors (which don't transform data) in a large state?

### ISSUE THREAD

**Issue by heloameneses** [reduxjs/reselect#444]
From [Motivation for Memoized Selectors](https://github.com/reduxjs/reselect#motivation-for-memoized-selectors):
> If the state tree is large, or the calculation expensive, repeating the calculation on every update may cause performance problems. Reselect can help to avoid these unnecessary recalculations.

Further, in [Creating a Memoized Selector](https://github.com/reduxjs/reselect#creating-a-memoized-selector):
> [...] `getVisibilityFilter` and `getTodos` are input-selectors. They are created as ordinary non-memoized selector functions because they do not transform the data they select.

Given a large state with 30 reducers and updated very frequently, is there a performance gain in memoizing 100+ input-selectors such as:
`state.preferences.theme`
`state.preferences.theme.color`
`state.preferences.theme.mode`
?

My question comes from reading:
> if the state tree is large, or the calculation expensive

It made me think that if the calculation is inexpensive - as in the case of input-selectors - but the state is large, it would make a case for memoization.

Thanks

**Comment by markerikson** [comment]
Memoizing selectors that consistently return the same values anyway provides no real benefit in terms of optimizations.

In this example, a selector that returns `state.preferences.theme` could be just a simple function like `state => state.preferences.theme`.

**Comment by heloameneses** [comment]
Without memoizing these simple input-selectors such as `state.preferences.theme`, if I log them, it will log when anything changes, and my state is updated every heartbeat.
So when `state.user` changes, I see `state.preferences.theme` logged.
Just to make sure this is not a big deal.

Would it be the same for simple computations such as `state => state.preferences.theme.mode === 'dark'`?

**Comment by markerikson** [comment]
The important thing for most selectors is that given the same input, they should return the same output reference.

For a simple lookup like `state => state.preferences.theme`, or even `(state, {id}) => state.todos[id]`, there's really not a need to memoize because it's going to return the same value until it changes.

However, _deriving_ data like `state => state.todos.map(todo => todo.name))` would create a new array reference every time, so memoizing the selector to only run the `map()` when `state.todos` changes would be important.

**Comment by heloameneses** [comment]
Thanks!
