### ISSUE TITLE
filtering works after sort but not before

### ISSUE THREAD

**Issue by goldylucks** [reduxjs/reselect#469]
I have a simple selector:

```js
export const selectSortedChats = createSelector(
  [selectContacts],
  chats => sortBy(chats, c => -last(c.messages).createdAt),
  contacts => contacts.filter(contact => !contact.isArchived), // works
)
```

but if I reverse it the filtering stops working:
```js
export const selectSortedChats = createSelector(
  [selectContacts],
  contacts => contacts.filter(contact => !contact.isArchived), // does nothing
  chats => sortBy(chats, c => -last(c.messages).createdAt),
)
```

Any clues to why this happens?

I'm using `sortBy` and `last` from `lodash`

Thanks for this awesome project :)

**Comment by joedski** [comment]
`createSelector()` has 2 different call styles that are equivalent in behavior:

1. `createSelector(...inputSelectorList, resultFunc)`, which accepts 1 or more inputs and a single result func at the end.
    - Example: `createSelector(selectContacts, selectOtherThing, keepShowableContacts)`
2. `createSelector(inputSelectorList, resultFunc)`
    - Example: `createSelector([selectContacts, selectOtherThing], keepShowableContacts)`

However, in your example, it looks like the two call styles are being mixed.  The behavior of calling `createSelector()` with an array followed by 2 or more functions is not defined, but what currently happens is this:

0. Let's start with one of the calls, `createSelector([selectContacts], sortChats, keepShowableContacts)`
1. [The last function, here `keepShowableContacts` is taken as the `resultFunc`](https://github.com/reduxjs/reselect/blob/e93fe66ea972cc9d012889238881acc6793cfb12/src/index.js#L55).
2. [The first argument gets checked for being an array or not](https://github.com/reduxjs/reselect/blob/e93fe66ea972cc9d012889238881acc6793cfb12/src/index.js#L37).  Since in these cases, it is indeed an array `[selectContacts]`, that is used as the `inputSelectorList`.
3. Becouse of the previous step, the second argument `sortChats` is discarded entirely.

**Comment by goldylucks** [comment]
thanks for the explanation :)
