### ISSUE TITLE
Not having an external types library prevents usage as a peerDependency in a TS library

### ISSUE THREAD

**Issue by nloding** [reduxjs/reselect#474]
This is related to issue #421. Without having externally defined types, reselect cannot be used as a peerDependency in a Typescript library. Moving the types to DT, or publishing a separate `@types/reselect` package would resolve this problem, I believe.

Recreating this bug is simple (I can provide a repo if needed).

1. Create a library (for instance with create-react-library)
2. Add reselect as a peerDependency
3. Create a selector and export it
4. Attempt to compile the types for your library

In my case, I was using the following command to export the types for my library:
`cross-env NODE_ENV=production tsc --project tsconfig.types.json`

I received the following error:
```
> cross-env NODE_ENV=production tsc --project tsconfig.types.json

src/selectors/locations.ts:1:32 - error TS2307: Cannot find module 'reselect' or its corresponding type declarations.

1 import { createSelector } from 'reselect'
```

**Comment by markerikson** [comment]
Uh... I'm admittedly not an expert on the nuances of typedefs and where they live, but how is moving the types _out_ of the library going to make a difference?  My vague understanding is that as long as there's an appropriate typedefs file pointed to by `package.json`, it doesn't matter whether a lib was written in TS and the typedefs output by TSC, or the typedefs were written by hand.

**Comment by nloding** [comment]
@markerikson I'm no expert at all either. I cannot say exactly why it's failing. I'll try to set up a repo to recreate the issue. My basic understanding is that, because peerDependencies aren't installed, there is no package.json to be referenced. Why it needs to be there for the types when it's a peerDependency, I don't know.

**Comment by markerikson** [comment]
@nloding the point of `peerDependencies` is that the package _is_ expected to be installed and available for reference, but the end user of `libraryA` is expected to see that `libraryB` is a peerDep of `A` and install `B` too.

Just listing a package as a peerDep does not magically make things work.

So, if `libraryB` references types or code from `libraryA`, both the TS compiler and the bundler actually need to go find and read the relevant files from `libraryA` off disk in order to properly parse/compile/load the imports.

Having said that, NPM 7 is apparently supposed to now install peerDeps by default.

This sounds like a misunderstanding of how lib dependencies work, rather than an actual bug with Reselect.

**Comment by nloding** [comment]
@markerikson it's entirely possible I'm not using peerDeps correctly! My client has two applications and a shared library between them. Both the applications and the library have a dependency on Reselect (as well as other packages), so we've put them under peerDependencies. It works with every library so far except Reselect.

Is the correct way to manage these dependencies to have it under both `dependencies` and `peerDependencies` then?

**Comment by markerikson** [comment]
The _library_ should list Reselect as a `peerDependency`, because it's not the library's job to ensure that package is installed.

The _application_ should listed Reselect as an actual `dependency`, because it's the application saying "yes, I actually require this library for our code".

Libraries may also list other libs as hard dependencies, depending on when and how the other libs are getting used.

But no, just listing stuff as `peerDeps` everywhere is not sufficient, because up until NPM 7, package managers have not installed `peerDeps` automatically.

**Comment by nloding** [comment]
I'm confused, I guess, because that sounds like exactly what we're doing. Reselect is a peerDependency in the library, it's a dependency in the application. And when trying to build it, we get the error I shared.

**Comment by markerikson** [comment]
Yeah, I'd really need to see specifics at this point to understand what you're doing and what's going on.
