### ISSUE TITLE
Multiple selectors with arguments result in a union type

### ISSUE THREAD

**Issue by strmer15** [reduxjs/reselect#540]
Typescript 4.4.2
Reselect 4.1.1

If I have a selector like:

```
export const testSelector = createSelector(
  (_: RootState, { testNumber }: { testNumber: number }) => testNumber,
  (_: RootState, { testString }: { testString: string }) => testString,
  (testNumber, testString) => testNumber + testString
)
```

When I try to call the selector using:

```
  const test = useSelector((state: RootState) =>
    testSelector(state, { testNumber: 1, testString: '10' })
  )
```

I get the error:

```
Argument of type '[{ testNumber: number; testString: string; }]' is not assignable to parameter of type '[{ testNumber: number; }] | [{ testString: string; }]'.
  Type '[{ testNumber: number; testString: string; }]' is not assignable to type '[{ testNumber: number; }]'.
    Type '{ testNumber: number; testString: string; }' is not assignable to type '{ testNumber: number; }'.
      Object literal may only specify known properties, and 'testString' does not exist in type '{ testNumber: number; }'. ts(2345)
```

It appears that Reselect is converting all the different arguments into a union type, when instead they should be combined using an intersection type.

Workaround is to drop back to Reselect 4.0.0, which uses the intersection type.

**Comment by ViktorQvarfordt** [comment]
I came here to create a new issue but I believe this issue describes the root cause. I paste my example here for reference. It all works on reselect 4.0 but not on 4.1. I believe my example covers some more incorrect errors than the post above.

The code still runs correctly on 4.1, so this seems to be purely at typing problem. Unfortunately, this is a blocker for us to use 4.1 in our codebase since we heavily rely on correct typing but we really want to use the new memoize options.

```ts
import { createSelector } from "reselect"


// Args

const select1Arg = createSelector(
  [
    (state, arg1) => state,
    (state, arg1) => arg1
  ],
  (state, arg1) => [state, arg1]
)

const select2Arg = createSelector(
  [
    (state, arg1, arg2) => state,
    (state, arg1, arg2) => arg1,
    (state, arg1, arg2) => arg2
  ],
  (state, arg1, arg2) => [state, arg1, arg2]
)

const select2ArgWrapped = createSelector(select2Arg, x => x)

console.log('select1Arg', select1Arg('state', 1))
console.log('select2Arg', select2Arg('state', 1, 2))
console.log('select2Wrapped', select2ArgWrapped('state', 1, 2))


// Props
console.log()

const select1Prop = createSelector(
  [
    (state, props) => state,
    (state, props) => props
  ],
  (state, props) => [state, props]
)

const select2Prop = createSelector(
  [
    (state, props) => state,
    (state, props) => props,
  ],
  (state, props) => [state, props]
)

const select2PropWrapped = createSelector(select2Prop, x => x)

console.log('select1Prop', select1Prop('state', { prop1: 1 }))
console.log('select2Prop', select2Prop('state', { prop1: 1, prop2: 2 }))
console.log('select2Wrapped', select2PropWrapped('state', { prop1: 1, prop2: 2 }))


// Args chained
console.log()

const select2ArgChained = createSelector(
  [
    select1Arg,
    (state, arg1, arg2) => arg2
  ],
  (state, arg2) => [state, arg2]
)

const select2ArgWrappedChained = createSelector(select2Arg, x => x)

console.log('select2ArgChained', select2ArgChained('state', 1, 2))
console.log('select2WrappedChained', select2ArgWrappedChained('state', 1, 2))


// Props chained
console.log()

const select2PropChained = createSelector(
  [
    select1Prop,
    (state, props) => props,
  ],
  (state, props) => [state, props]
)

const select2PropWrappedChained = createSelector(select2Prop, x => x)

console.log('select2PropChained', select2PropChained('state', { prop1: 1, prop2: 2 }))
console.log('select2WrappedChained', select2PropWrappedChained('state', { prop1: 1, prop2: 2 }))
```

Pasting a screenshot that highlights where the errors are. In the screenshot I hover on one particular error that I believe is distinct from what is described in the the post above. Let me know if I should open more issues.

![image](https://user-images.githubusercontent.com/344809/140571105-74d7e6cd-0771-4bc9-8cf3-8b96bca05457.png)

**Comment by markerikson** [comment]
I worked on this issue both last weekend and all of this weekend. I've got progress, but also roadblocks.

The good news is that I think I've got a reworked version of the parameters handling that correctly intersects the parameters at a given position, and passes both of the examples shown here.

Unfortunately, it's also failing another existing type test, because it's now also wiping out a valid use of a union type as an argument.  

Additionally, I'm now seeing "excessively deep instantiation" errors in some of our tests, like "ensure we can handle 20+ input selectors".

So, kind of between a rock and a hard place here. Fix this, break something else.

**Comment by ViktorQvarfordt** [comment]
Thanks for your efforts Mark! Perhaps reselect should revert back to the code from 4.0? It seems to be solid. We are now specifying version 4.0 explicitly in our dependencies. I consider > 4.0 broken at the moment.

**Comment by markerikson** [comment]
I would really rather not do that - the old types were _also_ effectively broken and impossible to maintain:

https://github.com/reduxjs/reselect/blob/v4.0.0/src/index.d.ts

There's no meaningful way to add the additional memoization options to those types.

**Comment by markerikson** [comment]
Part of the issue here is I don't think it's very well defined what the final generated selector's arguments should be based on the available input selectors.

For "params at the same index of each input selector", the obvious properties are:

- All params are the same: use that type
- Params are objects: intersect them so that all fields must be included
- Params are incompatible (say, `string` and `number`): use `never` so that there's an error
- One selector is longer than another, so that `params1[3]` is `string` but `params2[3]` is `undefined`: use the value

So far, these are all reasonably accomplished with `UnionToIntersection<>`.  

The problem comes when some of the parameters are unions themselves.  For example, even just _one_ selector like `(key: keyof SomeObj) => whatever`, or `(val: string | number) => whatever`.  When `UnionToIntersection` gets applied here, the union in that parameter gets intersected, and thus ends up as `never` for what would have been a perfectly valid input argument.

As a more specific example, for this selector:

```ts
const input1a = (
  _: StateA,
  { testNumber }: { testNumber: number },
  c: number,
  d: string
) => testNumber

const input1b = (
  _: StateA,
  { testString }: { testString: string },
  c: number
) => testString

const input1c = (
  _: StateA,
  { testBoolean }: { testBoolean: boolean },
  c: number | string,
  d: string
) => testBoolean

const input1d = (_: StateA, { testString2 }: { testString2: string }) =>
  testString2

const testSelector = createSelector(
  input1a,
  input1b,
  input1c,
  input1d,
  (testNumber, testString, testBoolean) => testNumber + testString
)
```

the parameters arrays are:

```ts
[
  [StateA, { testNumber: number; }, number, string], 
  [StateA, {  testString: string; }, number], 
  [StateA, { testBoolean: boolean; }, string | number, string], 
  [StateA, {  testString2: string; }]
]
```

If we transpose them to extract the types at each parameter index, we get:

```
[
  [StateA, StateA, StateA, StateA],
  [{testNumber: number}, {testString: string}, {testBoolean: boolean}, {testString2: string}],
  [number, number, string | number, undefined],
  [string, undefined, string, undefined]
]
```

The first two are easy: `StateA` and `{testNumber, testString, testBoolean, testString2}`.  The third _should_ end up as `string | number`, and the fourth _should_ end up as `string`.

But, because we need to apply `UnionToIntersection` on the entire array, the third one actually ends up as a union of `string | string | number` -> `string | number`, and intersectioned that becomes `never`.

So. What I've got locally solves the problems listed in this issue, #541, and #548 .  But, it also results in a `never` any time there's a legitimate union being passed as a parameter type.

I could clean up what I've got and put out an alpha release to let folks try it out, I guess. I'm just trying to figure out if there's any viable options for fixing the union/intersection issue here.

**Comment by markerikson** [comment]
Update: after some major help from @Retsam and @pfgray , we _may_ have something that seems to be A) passing all our type tests, and B) _not_ killing TS with excessively deep processing.

The current branch is incredibly hacked up and I'll really need to start from scratch with the final approach in mind, but I think we might actually be on to something here.

**Comment by markerikson** [comment]
Out in https://github.com/reduxjs/reselect/releases/tag/v4.1.3
