### ISSUE TITLE
JetBrains WebStorm no longer highlights fields in selector function

### ISSUE THREAD

**Issue by spencerr-carimus** [reduxjs/reselect#547]
On `4.0.0`:
`createSelector` references `reselect/lib/index.d.ts`
```
export function createSelector<S, R1, T>(
  selector: Selector<S, R1>,
  combiner: (res: R1) => T,
): OutputSelector<S, T, (res: R1) => T>;
```
![image](https://user-images.githubusercontent.com/28570856/141500372-09391c3a-922f-4cb5-a60a-ddb98a6d9ab9.png)

On `4.1.2`:
`createSelector` references `reselect/src/index.ts`
```
export const createSelector =
  /* #__PURE__ */ createSelectorCreator(defaultMemoize)
```
![image](https://user-images.githubusercontent.com/28570856/141500462-5bf34ea5-8dc7-49fd-b001-1a1e1d165c47.png)

**Comment by markerikson** [comment]
My experience has been that WebStorm (and other JetBrains IDEs) simply have inferior TypeScript support and do not work correctly in all situations.

That said, I think the real problem here is that your `getInstitutionsState` selector isn't actually typed at all.  You _need_ to correctly declare types for all input selectors in order for TS to correctly infer the types of the arguments to the output selector.
