### ISSUE TITLE
Reselect with Immer not playing well together?

### ISSUE THREAD

**Issue by jtwigg** [reduxjs/reselect#562]
I'm using `createSelector` along with `createReducer/createSlice` function provided by Redux Toolkit.
This backed by Immer, and it allows me to directly mutate state in reducers. Very useful.
https://redux-toolkit.js.org/api/createReducer#direct-state-mutation

However I'm finding that because it ALWAYS returns a new state, it makes `createSelector` useless, because even a deeply nested toggle to a boolean, causes a whole new State object to be returned, and so it fails the `===` test that Reselect relies on.

Below is an example
```
export interface CounterState {
    value: number
    items: Items[]
}

export interface Items {
    enabled: boolean
}

const initialState: CounterState = {
    value: 0,
    items: []
}

export const counterSlice = createSlice({
    name: 'counter',
    initialState,
    reducers: {
        toggleLast: (state) => {
            state.items[state.items.length - 1].enabled = !state.items[state.items.length - 1].enabled
        },
        add: (state) => {
            state.items.push({ enabled: false })
        },
    },
})
```

and UI
```
import { RootState } from './store'
import { useSelector, useDispatch } from 'react-redux'
import { add, Items, toggleLast } from './counterSlice'
import { createSelector } from "@reduxjs/toolkit";

let items: Items[] = []
const selectedItems = createSelector(
    (state: RootState) => {
        if (items === state.counter.items) {
            console.log("Same")
        } else {
            console.log("Diff")
        }
        items = state.counter.items
        return state.counter.items
    },
    (items) => {
        return items.filter(x => x.enabled).length
    }
)


export function Counter() {
    const selectedItemCount = useSelector(selectedItems)
    const itemsCount = useSelector<RootState>((state) => state.counter.items.length)
    const dispatch = useDispatch()

    console.log("Render")
    return (
        <div>
            <div>
                <button
                    aria-label="Add"
                    onClick={() => dispatch(add())}
                >
                    Add
                </button>
                <button
                    aria-label="Toggle"
                    onClick={() => dispatch(toggleLast())}
                >
                    Toggle
                </button>
                <span>Selected:{selectedItemCount}</span>

                <span>Total:{itemsCount}</span>

            </div>
        </div>
    )
}
```

There's some test code that shows that, the `item[]` are always in a new array, even when just a `toggle` call is made (`item[items.count-1].enabled  = !enabled`)

**Do `Immer` and `Reselect` not work well together? Anyone have any experience with the new?**

**Comment by markerikson** [comment]
To be clear, **immutable updates _always_ require returning new references for _every_ level of nesting being updated**:

- https://redux.js.org/usage/structuring-reducers/immutable-update-patterns#updating-nested-objects

Immer just makes that process simpler to write.

It's worth noting that `createSelector` runs two different checks internally:

- First, are all of the input arguments the same as last time?  If so, it can bail out right away
- Second, if any of the arguments are different, it will call all of the "input selectors".  It then takes all of their return values, and checks to see if any of _those_ have changed.

`createSelector` will only actually run the "output selector" if at least one of the extracted values have changed.

So, yes, I would fully expect that the `rootState` check would almost always show that it's a different value. That's how immutable updates work, and that's how Redux works.

What matters from there is how often the _output selector_ gets run. If you move your logging down into that function, you should see that it does not re-run if other parts of the state change - only when `state.counter.items` is updated in some way.  But, per the earlier comment, updating one field in one of those items _will_ cause the creation of a new `item` object, a new `items` array, a new `counter` object, and a new `state` object.  So, flipping `counterState.items[3].enabled = false` would generate a new `counterSlice.items` array, and thus cause the output selector to re-run.

So, yes, this is all expected behavior because of how immutable updates work, and not anything specific to Immer.

You might want to take a glance at these resources:

- https://daveceddia.com/react-redux-immutability-guide/
- https://redux.js.org/usage/structuring-reducers/immutable-update-patterns
- https://redux.js.org/usage/deriving-data-selectors

The one other note here is that this can lead to situations where the output selector is forced to re-run, even though the output ends up being conceptually similar to before. As an example, picture an output selector of `(todos) => todos.map(todo => todo.id)`, and then flip one `todo.completed` flag.  New `todo` object, new `todos` array, so the output selector reruns... but all of the todos still have the same ids.  So, the previous and new `todoIds` arrays are shallow equal to each other (all the same contents), but are different references. This _can_ lead to some unnecessary re-rendering.

That's why Reselect 4.1 added the ability to customize output result comparisons. In this situation, we could use `shallowEqual` as a way to compare the old and new `todoIds` arrays, and if they're equivalent it will reuse the old array reference.

See https://github.com/reduxjs/reselect/releases/tag/v4.1.0 for some more details.
