### ISSUE TITLE
Type inference regression in 4.1.5

### ISSUE THREAD

**Issue by leonovalex** [reduxjs/reselect#565]
Following code works fine in 4.0.0 but failed in 4.1.5

```typescript
import { createSelector, createStructuredSelector, Selector } from 'reselect';

type State = { a: boolean, b: string }

type Props = { a1: boolean, b1: string }

const createPropsSelector = <T extends object>(selector: ((x: T) => State)): Selector<T, Props> => {
    const a1 = createSelector(selector, x => x.a);
    const b1 = createSelector(selector, x => x.b);
    return createStructuredSelector<T, Props>({ a1, b1 }) // <-- error here with 4.1.5
}

// Usages
type MegaState = { states: State[], active: number }
const stateSelector1: Selector<MegaState, Props> = createPropsSelector((x: MegaState) => x.states[x.active])
const stateSelector2: Selector<State, Props> = createPropsSelector((x: State) => x)
```

**Comment by markerikson** [comment]
@leonovalex can you be more specific about what "fails"?

The snippet is helpful, but could you put it in a CodeSandbox that specifically demonstrates the issue, including a `tsconfig.json`?

**Comment by leonovalex** [comment]
Hi @markerikson

My fault, "fails" mean "fails to compile/typecheck/infer types.

Here link to sandbox https://codesandbox.io/s/withered-glade-kdu48?file=/src/index.ts

**Comment by leonovalex** [comment]
Is there any way to avoid error there and control selector's `Result` follows given `Props`?

**Comment by markerikson** [comment]
I think the correct answer here is to stop specifying all the generics.  If I remove all of them, this type-checks correctly:

```ts
const createPropsSelector = <T extends object>(
  selector: (x: T) => State
)=> {
  const a1 = createSelector(selector, (x) => x.a);
  const b1 = createSelector(selector, (x) => x.b);
  return createStructuredSelector({ a1, b1 }); // <-- error here with 4.1.5
};

// Usages
type MegaState = { states: State[]; active: number };
const stateSelector1 = createPropsSelector(
  (x: MegaState) => x.states[x.active]
);
const stateSelector2= createPropsSelector(
  (x: State) => x
);


/*
const stateSelector1: (state: {
    states: State[];
    active: number;
}) => {
    a1: boolean;
    b1: string;
}
*/
```

**Comment by leonovalex** [comment]
Originally `Props` (aka extra generics) were added to fix selector's type because it might be much-much complex. 
For example we may need to pass result into function's argument `Selector<MegaState, Props>` and compilation will be broken again.
And it is the original question: how to create selector with predefined type `Selector<T, Props>` in newer versions.
There is significant codebase followed this approach. If it is impossible I believe it should be marked as breaking change.
And should have new major version to avoid upgrading to not compatible version.

**Comment by markerikson** [comment]
@leonovalex : I'd have to disagree on that last part.

Defining what "semver" means for TS types is difficult, especially because TS itself doesn't follow semver.  Technically _any_ change we release _might_ end up breaking someone's build.

I covered some of this in my recent talk [Lessons from Maintaining TS Libraries](https://blog.isquaredsoftware.com/2022/05/presentations-ts-lib-maintenance/), and specifically pointing to the work the Ember community has put together over at https://www.semver-ts.org/ .

As a TL;DR, my own stance is that as long as we are _trying_ to actually maintain types compatibility with existing code, we will stick with minors and patch releases.  If you look through all of the work that's been done on the 4.1.x line, we've been testing against a fairly large set of "type tests" for different usage scenarios in order to keep compatibility with things we know users are doing.

On the other hand, some of the inference techniques we're using in 4.1.x require that you do _not_ supply explicit generic arguments.  That means that while there may be some compile errors, the solution is to _delete_ the explicit generics in your code.  To me that qualifies as "a fix" to our types, not "a breaking change".

If removing those generics does not solve the original issue we can discuss further, but based on my testing it appears to resolve the problem.

**Comment by Jef-Z** [comment]
Hi, @markerikson 
Thanks for your answer and contribution.
The new version of the createStructuredSelector type becomes something like the following, which is really bad. It cannot be read pleasantly:
![image](https://github.com/reduxjs/reselect/assets/45141759/88dea961-f16a-4b32-b740-9ddcc7304f34)

The new version has good type inference. But we need type constraints, not inferences. If we change a key incorrectly, then the type inference results in the wrong key.

An example
Now I wrote a `createStructuredSelector`:

```
const mapStateToProps = createStructuredSelector({
  flights: selectFlights,
});
```

Now `mapStateToProps` is inferred as:

![image](https://github.com/reduxjs/reselect/assets/45141759/99e14adf-2e22-4435-8cde-799da66dfa3f)

Let's modify `flights` to `fli`,The new inferred type is:

![image](https://github.com/reduxjs/reselect/assets/45141759/0597bf9a-6bdd-4e19-9fdd-97d6a4090314)

You know. This is the wrong return result. As stated in @leonovalex 's example. Older versions of the type inference tool could simply be constrained using generics:
```
createStructuredSelector<T, Props>
```

If the `flights` were in `Props`, the type would report an error when I mistakenly changed it to `fli`.
But the new version of the type is too complex. **Do you have any good type suggestions?**

**Comment by aryaemami59** [comment]
@Jef-Z You can now use the [`createStructuredSelector.withTypes<RootState>()`](https://reselect.js.org/api/createStructuredSelector#defining-a-pre-typed-createstructuredselector) to create a "pre-typed" version of [`createStructuredSelector`](https://reselect.js.org/api/createStructuredSelector).

```ts
export const createStructuredAppSelector =
  createStructuredSelector.withTypes<RootCheckoutState>()
```

then you can do this:

```ts
const mapStateToProps = createStructuredAppSelector({
  flights: selectFlights,
})
```

**Comment by EskiMojo14** [comment]
@Jef-Z if you want to make sure your selector result matches a specific shape, you can use a utility like this: https://tsplay.dev/wOVarW

```ts
type SelectorMap<State, Result> = {
  [K in keyof Result]: Selector<State, Result[K]>;
};

const selectCount = (state: RootState) => state.counter.value;

const test = createStructuredSelector({
  count: selectCount,
} satisfies SelectorMap<RootState, { counter: number }>);
```

**Comment by markerikson** [comment]
I'll also point out that this issue was closed 2 years ago, and i don't think the `createStructuredSelector` thing mentioned has anything to do with the original issue :)
