### ISSUE TITLE
force cache clear not working using clearCache method.

### ISSUE THREAD

**Issue by Tanmay2711** [reduxjs/reselect#568]
Hi Team,

We have react application and I am using createSelector function from redux/toolkit to create memoize selector to select data provided by React Context provider. On Component load in useEffect i am calling selector.clearCache(), but its not working.
its still returned cache data if component unloaded and loaded again and selector provided with same input arguments

Here is the code.

Memoize selector
import { createSelector } from '@reduxjs/toolkit';
![image](https://user-images.githubusercontent.com/48334190/157473804-425b796f-a86b-455c-ac18-ae83608930c3.png)

trying to clear cache in component first time render -
![image](https://user-images.githubusercontent.com/48334190/157474204-727e1398-dcdc-44f8-a09a-6e6ee394598c.png)

Redux toolkit version -
![image](https://user-images.githubusercontent.com/48334190/157474687-bd2633cd-82f2-4dd1-84c8-ee6e76e054ee.png)
![image](https://user-images.githubusercontent.com/48334190/157474820-7f18e89b-cc54-45bf-8183-baf457b7b2c9.png)

**Comment by markerikson** [comment]
I think the issue here is that the memoize function gets used _twice_ internally: once to memoize against the incoming arguments, and then again to memoize the actual extracted values vs the final result.

That results in _two_ different `.clearCache` functions: `selectThing.clearCache`, and `selectThing.memoizedResultFunc.clearCache`.  

Try calling `selectThing.memoizedResultFunc.clearCache()` instead and see what happens.
