### ISSUE TITLE
Is it safe to use hooks in createSelector?

### ISSUE THREAD

**Issue by adefrutoscasado** [reduxjs/reselect#577]
I have just found out (at this issue: https://github.com/reduxjs/redux-toolkit/issues/1401) that it's possible to use data hooks in `createSelector` functions and it works. An example:

```js
// This is a normal hook
const useUserReducer = () => {
  const userAccessData = useSelector(state => state?.userAccessData)
  return userAccessData
}

// Here I use the hook as first argument!
export const useUserReducerFromCreateSelector = createSelector(useUserReducer, (result) => {
  console.log(result) // userAccessData printed correctly
  return result
})
```

Then I use it in my component as a normal hook:

```jsx
const Component = () => {
  const result = useUserReducerFromCreateSelector([])
  console.log(result) // userAccessData printed correctly
  return (
    <>
      {JSON.stringify(result)}
    </>
  )
}
```

I dont see any documentation about this, so I wonder if its safe to use it. It would help me a lot creating reusable selectors.

Versions:
- @reduxjs/toolkit 1.8.1 > reselect 4.1.5

**Comment by markerikson** [comment]
**No, this is _not_ safe!**

You're technically getting away with it because of how you're using that in a component.  But if you were to try to use that selector outside of a component, it would break.

I'd really recommend sticking with keeping these concepts separate.  Write and name selectors as selectors.  Write and name hooks as hooks.  Don't try and mix the two :)
